stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install -r requirements.txt

test:
  stage: test
  before_script:
    - setup_test_environment_script.sh
  script:
    - pytest PSS_microservice/tests.py
