image: python:3.11.7

stages:
  - lint
  - test
  - build_image
  - push_image

before_script:
  - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.7
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r PSS_microservice/requirements.txt

variables:
  PYTHON_VERSION: "3.11.7"

run_tests:
  stage: test
  script:
    - python3 pytest

  only:
    - branches  

  except:
    - master 

