
stages:
  - test
  - build

variables:
  PYTHON_VERSION: "3.11.7"

run_tests:
  stage: test
  
  image: python:$PYTHON_VERSION
  services:
   - rabbitmq:latest

  variables:
    RABBITMQ_DEFAULT_PORT: 5672
  
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r ./requirements.txt
  
  script:
    - pytest tests
    - pytest PSS_microservice/tests
    - pytest PSP_microservice/tests

  only:
    - branches  
  except:
    - master 



# build_image:
#   stage: build

#   image: docker:24
#   services:
#     - docker:24-dind
#   variables:
#     DOCKER_TLS_CERTDIR: "/certs"
#     HARBOR_USER: sh06
#     IMAGE_NAME: harbor.peak.scot/sh06/pss_microservice
#     IMAGE_TAG: latest
  
#   before_script:
#     - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD harbor.peak.scot
  
#   script:
#     - docker build -t $IMAGE_NAME:$IMAGE_TAG .
#     - docker push $IMAGE_NAME:$IMAGE_TAG
