
stages:
  - lint
  - test
  - image

variables:
  PYTHON_VERSION: "3.11.7"
  HARBOR_USER: sh06
  IMAGE_NAME: harbor.peak.scot/sh06/pss_microservice
  IMAGE_TAG: latest

run_tests:
  stage: test
  
  image: python:$PYTHON_VERSION
  
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r ./requirements.txt
  
  script:
    - pytest

  only:
    - branches  
  except:
    - master 

build_image:
  stage: image

  image: docker:25.0.0
  services:
    - docker:25.0.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $HARBOR_USER -p '$HARBOR_PASSWORD' $HARBOR_REGISTRY
  
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
