image: python:3.11.7

stages:
  - lint
  - test
  - build_image
  - push_image

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r PSS_microservice/requirements.txt

variables:
  PYTHON_VERSION: "3.11.7"

run_tests:
  stage: test
  script:
    - pytest

  only:
    - branches  

  except:
    - master 

