image: python:latest

stages:
  - test

before_script:
  - apt-get install -y python3.11.5
  - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r PSS_microservice/requirements.txt

variables:
  PYTHON_VERSION: "3.11.5"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r PSS_microservice/requirements.txt

test:
  stage: test
  script:
    - unittest PSS_microservice/tests.py

  only:
    - branches  

  except:
    - master 

