stages:
  - test

variables:
  PYTHON_VERSION: "3.11.5"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest PSS_microservice/tests.py

  only:
    - branches  

  except:
    - master 
