
stages:
  - test
  - build
  - release

variables:
  PYTHON_VERSION: "3.11.7"

run_tests:
  stage: test
  
  image: python:$PYTHON_VERSION
  
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r ./requirements.txt
  
  script:
    - pytest

  only:
    - branches  
  except:
    - master 

# build_image:
#   stage: build

#   image: docker:24
#   services:
#     - docker:24-dind
#   variables:
#     DOCKER_TLS_CERTDIR: "/certs"
#     HARBOR_USER: sh06
#     IMAGE_NAME: harbor.peak.scot/sh06/pss_microservice
#     IMAGE_TAG: latest
  
#   before_script:
#     - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD harbor.peak.scot
  
#   script:
#     - docker build -t $IMAGE_NAME:$IMAGE_TAG .
#     - docker push $IMAGE_NAME:$IMAGE_TAG

# build_cli_linux:



build_cli_windows:
  stage: build
  image: python:3.11-windowsservercore
  script:
    - pip install pyinstaller
    - pyinstaller --onefile --distpath ".\temp\win\dist" --workpath ".\temp\win\build" --specpath ".\temp\win" --name ProteinCLI "cli\ProteinClient.py"
  artifacts:
    - .\temp\win\dist\ProteinClient.exe
  only:
    - main
    - feature/pipeline/master


# release_cli_linux:
#   stage: release

# release_cli_windows:
#   stage: release
