version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "80:27017"
    #restart: always


  myapp:
    
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./main.py:/src/main.py
  
  mongo_express:
    image: mongo-express

    ports:
      - 5999:6000
  