version: "3.8"
services:
  mongodb:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - protein_collection:/data/db
    
  myapp:
    build: . 
    ports:
      - 8085:8086
    environment:
      DB_URL: mongodb://db/protein_collection
  
  mongoexpress:
    image: mongo-express
    ports:
      - "2000:5000"
    volumes:
      - protein_collection:/data/db

volumes:
  protein_collection: 

  